-- ADD THE NEW FIELD TO KNOWN THE LOCATION OF THE ACCOUNT --
ALTER TABLE Account ADD country VARCHAR(64) NOT NULL DEFAULT 'NO COUNTRY SPECIFIED';

-- CREATE TABLE TO STORAGE COUNTRIES --
CREATE TABLE Country (id VARCHAR(64) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

-- FUNCTION TO SET A RANDOM COUNTRY TO ALL 'NO COUNTRY SPECIFIED' ACCOUNTS --
CREATE OR REPLACE FUNCTION RandomizeNoCountryAccounts() 
    RETURNS VOID
AS $$
DECLARE
    t_curs CURSOR FOR 
        SELECT * FROM Account 
        WHERE country = 'NO COUNTRY SPECIFIED';
    t_row VARCHAR(64);
BEGIN
    FOR t_row IN t_curs LOOP
        UPDATE Account
            SET country = (SELECT name FROM Country ORDER BY random() LIMIT 1)
        WHERE CURRENT OF t_curs;
    END LOOP;
END;
$$ 
LANGUAGE plpgsql;
